import { CURRENT_YEAR } from '@/shared/model/index.constants';
import { InputType } from '@/shared/model/index.types';
import { Platform } from 'react-native';

// Input 컴포넌트 관련 맵
export const textInputAttrSettingMap: Record<InputType, object> = {
  text: { keyboardType: 'default' },
  password: {
    keyboardType: 'default',
    secureTextEntry: true,
    autoCapitalize: 'none',
    autoComplete: 'password',
    textContentType: 'password',
  },
  email: {
    keyboardType: 'email-address',
    autoCapitalize: 'none',
    autoComplete: 'email',
    textContentType: 'emailAddress',
  },
  number: {
    keyboardType: Platform.OS === 'ios' ? 'number-pad' : 'numeric',
    autoCapitalize: 'none',
  },
  decimal: {
    keyboardType: 'decimal-pad',
    autoCapitalize: 'none',
  },
  tel: {
    keyboardType: 'phone-pad',
    autoCapitalize: 'none',
    autoComplete: 'tel',
    textContentType: 'telephoneNumber',
  },
  url: {
    keyboardType: 'url',
    autoCapitalize: 'none',
    autoComplete: 'off',
    textContentType: 'URL',
  },
  search: {
    keyboardType: 'default',
    returnKeyType: 'search',
    autoCapitalize: 'none',
  },
  username: {
    keyboardType: 'default',
    autoCapitalize: 'none',
    autoComplete: 'username',
    textContentType: 'username',
  },
  name: {
    keyboardType: 'default',
    autoCapitalize: 'words',
    autoComplete: 'name',
    textContentType: 'name',
  },
};

// Date 배열
export const yearList = Array.from({ length: 100 }, (_, i) => {
  const year = CURRENT_YEAR - i;
  return { label: `${year}년`, value: year };
});

export const monthList = Array.from({ length: 12 }, (_, i) => {
  const month = i + 1;
  return { label: `${month}월`, value: month };
});

// Address 배열
export const guList = [
  { label: '강남구', value: '강남구' },
  { label: '강동구', value: '강동구' },
  { label: '강북구', value: '강북구' },
  { label: '강서구', value: '강서구' },
  { label: '관악구', value: '관악구' },
  { label: '광진구', value: '광진구' },
  { label: '구로구', value: '구로구' },
  { label: '금천구', value: '금천구' },
  { label: '노원구', value: '노원구' },
  { label: '도봉구', value: '도봉구' },
  { label: '동대문구', value: '동대문구' },
  { label: '동작구', value: '동작구' },
  { label: '마포구', value: '마포구' },
  { label: '서대문구', value: '서대문구' },
  { label: '서초구', value: '서초구' },
  { label: '성동구', value: '성동구' },
  { label: '성북구', value: '성북구' },
  { label: '송파구', value: '송파구' },
  { label: '양천구', value: '양천구' },
  { label: '영등포구', value: '영등포구' },
  { label: '용산구', value: '용산구' },
  { label: '은평구', value: '은평구' },
  { label: '종로구', value: '종로구' },
  { label: '중구', value: '중구' },
  { label: '중랑구', value: '중랑구' },
];
export const dongMap: Record<string, { label: string; value: string }[]> = {
  강남구: [
    { label: '개포동', value: '개포동' },
    { label: '논현동', value: '논현동' },
    { label: '대치동', value: '대치동' },
    { label: '도곡동', value: '도곡동' },
    { label: '삼성동', value: '삼성동' },
    { label: '세곡동', value: '세곡동' },
    { label: '신사동', value: '신사동' },
    { label: '압구정동', value: '압구정동' },
    { label: '역삼동', value: '역삼동' },
    { label: '율현동', value: '율현동' },
    { label: '일원동', value: '일원동' },
    { label: '자곡동', value: '자곡동' },
    { label: '청담동', value: '청담동' },
  ],
  강동구: [
    { label: '강일동', value: '강일동' },
    { label: '고덕동', value: '고덕동' },
    { label: '길동', value: '길동' },
    { label: '둔촌동', value: '둔촌동' },
    { label: '명일동', value: '명일동' },
    { label: '상일동', value: '상일동' },
    { label: '성내동', value: '성내동' },
    { label: '암사동', value: '암사동' },
    { label: '천호동', value: '천호동' },
  ],
  강북구: [
    { label: '미아동', value: '미아동' },
    { label: '번동', value: '번동' },
    { label: '삼양동', value: '삼양동' },
    { label: '송중동', value: '송중동' },
    { label: '송천동', value: '송천동' },
    { label: '수유동', value: '수유동' },
    { label: '우이동', value: '우이동' },
  ],
  강서구: [
    { label: '가양동', value: '가양동' },
    { label: '개화동', value: '개화동' },
    { label: '공항동', value: '공항동' },
    { label: '과해동', value: '과해동' },
    { label: '내발산동', value: '내발산동' },
    { label: '등촌동', value: '등촌동' },
    { label: '마곡동', value: '마곡동' },
    { label: '방화동', value: '방화동' },
    { label: '염창동', value: '염창동' },
    { label: '오곡동', value: '오곡동' },
    { label: '오쇠동', value: '오쇠동' },
    { label: '외발산동', value: '외발산동' },
    { label: '화곡동', value: '화곡동' },
  ],
  관악구: [
    { label: '낙성대동', value: '낙성대동' },
    { label: '난곡동', value: '난곡동' },
    { label: '난향동', value: '난향동' },
    { label: '남현동', value: '남현동' },
    { label: '대학동', value: '대학동' },
    { label: '미성동', value: '미성동' },
    { label: '보라매동', value: '보라매동' },
    { label: '삼성동', value: '삼성동' },
    { label: '서림동', value: '서림동' },
    { label: '서원동', value: '서원동' },
    { label: '성현동', value: '성현동' },
    { label: '신림동', value: '신림동' },
    { label: '신사동', value: '신사동' },
    { label: '은천동', value: '은천동' },
    { label: '인헌동', value: '인헌동' },
    { label: '조원동', value: '조원동' },
    { label: '중앙동', value: '중앙동' },
    { label: '청룡동', value: '청룡동' },
    { label: '행운동', value: '행운동' },
  ],
  광진구: [
    { label: '광장동', value: '광장동' },
    { label: '구의동', value: '구의동' },
    { label: '군자동', value: '군자동' },
    { label: '능동', value: '능동' },
    { label: '자양동', value: '자양동' },
    { label: '중곡동', value: '중곡동' },
    { label: '화양동', value: '화양동' },
  ],
  구로구: [
    { label: '가리봉동', value: '가리봉동' },
    { label: '개봉동', value: '개봉동' },
    { label: '고척동', value: '고척동' },
    { label: '구로동', value: '구로동' },
    { label: '궁동', value: '궁동' },
    { label: '신도림동', value: '신도림동' },
    { label: '오류동', value: '오류동' },
    { label: '온수동', value: '온수동' },
    { label: '천왕동', value: '천왕동' },
    { label: '항동', value: '항동' },
  ],
  금천구: [
    { label: '가산동', value: '가산동' },
    { label: '독산동', value: '독산동' },
    { label: '시흥동', value: '시흥동' },
  ],
  노원구: [
    { label: '공릉동', value: '공릉동' },
    { label: '상계동', value: '상계동' },
    { label: '월계동', value: '월계동' },
    { label: '중계동', value: '중계동' },
  ],
  도봉구: [
    { label: '도봉동', value: '도봉동' },
    { label: '방학동', value: '방학동' },
    { label: '쌍문동', value: '쌍문동' },
    { label: '창동', value: '창동' },
  ],
  동대문구: [
    { label: '답십리동', value: '답십리동' },
    { label: '신설동', value: '신설동' },
    { label: '용두동', value: '용두동' },
    { label: '이문동', value: '이문동' },
    { label: '장안동', value: '장안동' },
    { label: '전농동', value: '전농동' },
    { label: '제기동', value: '제기동' },
    { label: '청량리동', value: '청량리동' },
    { label: '회기동', value: '회기동' },
    { label: '휘경동', value: '휘경동' },
  ],
  동작구: [
    { label: '노량진동', value: '노량진동' },
    { label: '대방동', value: '대방동' },
    { label: '동작동', value: '동작동' },
    { label: '본동', value: '본동' },
    { label: '사당동', value: '사당동' },
    { label: '상도동', value: '상도동' },
    { label: '신대방동', value: '신대방동' },
    { label: '흑석동', value: '흑석동' },
  ],
  마포구: [
    { label: '공덕동', value: '공덕동' },
    { label: '구수동', value: '구수동' },
    { label: '노고산동', value: '노고산동' },
    { label: '당인동', value: '당인동' },
    { label: '대흥동', value: '대흥동' },
    { label: '도화동', value: '도화동' },
    { label: '동교동', value: '동교동' },
    { label: '마포동', value: '마포동' },
    { label: '망원동', value: '망원동' },
    { label: '상수동', value: '상수동' },
    { label: '상암동', value: '상암동' },
    { label: '서교동', value: '서교동' },
    { label: '성산동', value: '성산동' },
    { label: '신공덕동', value: '신공덕동' },
    { label: '신수동', value: '신수동' },
    { label: '아현동', value: '아현동' },
    { label: '연남동', value: '연남동' },
    { label: '염리동', value: '염리동' },
    { label: '용강동', value: '용강동' },
    { label: '중동', value: '중동' },
    { label: '창전동', value: '창전동' },
    { label: '토정동', value: '토정동' },
    { label: '하중동', value: '하중동' },
    { label: '합정동', value: '합정동' },
    { label: '현석동', value: '현석동' },
  ],
  서대문구: [
    { label: '남가좌동', value: '남가좌동' },
    { label: '냉천동', value: '냉천동' },
    { label: '대현동', value: '대현동' },
    { label: '미근동', value: '미근동' },
    { label: '봉원동', value: '봉원동' },
    { label: '북가좌동', value: '북가좌동' },
    { label: '북아현동', value: '북아현동' },
    { label: '신촌동', value: '신촌동' },
    { label: '연희동', value: '연희동' },
    { label: '영천동', value: '영천동' },
    { label: '충정로동', value: '충정로동' },
    { label: '합동', value: '합동' },
    { label: '현저동', value: '현저동' },
    { label: '홍은동', value: '홍은동' },
    { label: '홍제동', value: '홍제동' },
  ],
  서초구: [
    { label: '내곡동', value: '내곡동' },
    { label: '반포동', value: '반포동' },
    { label: '방배동', value: '방배동' },
    { label: '서초동', value: '서초동' },
    { label: '신원동', value: '신원동' },
    { label: '양재동', value: '양재동' },
    { label: '염곡동', value: '염곡동' },
    { label: '우면동', value: '우면동' },
    { label: '원지동', value: '원지동' },
    { label: '잠원동', value: '잠원동' },
  ],
  성동구: [
    { label: '금호동', value: '금호동' },
    { label: '도선동', value: '도선동' },
    { label: '마장동', value: '마장동' },
    { label: '사근동', value: '사근동' },
    { label: '상왕십리동', value: '상왕십리동' },
    { label: '성수동', value: '성수동' },
    { label: '송정동', value: '송정동' },
    { label: '옥수동', value: '옥수동' },
    { label: '왕십리동', value: '왕십리동' },
    { label: '하왕십리동', value: '하왕십리동' },
    { label: '행당동', value: '행당동' },
    { label: '홍익동', value: '홍익동' },
  ],
  성북구: [
    { label: '길음동', value: '길음동' },
    { label: '돈암동', value: '돈암동' },
    { label: '동선동', value: '동선동' },
    { label: '동소문동', value: '동소문동' },
    { label: '보문동', value: '보문동' },
    { label: '삼선동', value: '삼선동' },
    { label: '석관동', value: '석관동' },
    { label: '성북동', value: '성북동' },
    { label: '안암동', value: '안암동' },
    { label: '장위동', value: '장위동' },
    { label: '정릉동', value: '정릉동' },
    { label: '종암동', value: '종암동' },
    { label: '하월곡동', value: '하월곡동' },
    { label: '상월곡동', value: '상월곡동' },
  ],
  송파구: [
    { label: '가락동', value: '가락동' },
    { label: '거여동', value: '거여동' },
    { label: '마천동', value: '마천동' },
    { label: '문정동', value: '문정동' },
    { label: '방이동', value: '방이동' },
    { label: '삼전동', value: '삼전동' },
    { label: '석촌동', value: '석촌동' },
    { label: '송파동', value: '송파동' },
    { label: '신천동', value: '신천동' },
    { label: '오금동', value: '오금동' },
    { label: '잠실동', value: '잠실동' },
    { label: '풍납동', value: '풍납동' },
  ],
  양천구: [
    { label: '목동', value: '목동' },
    { label: '신월동', value: '신월동' },
    { label: '신정동', value: '신정동' },
  ],
  영등포구: [
    { label: '당산동', value: '당산동' },
    { label: '대림동', value: '대림동' },
    { label: '도림동', value: '도림동' },
    { label: '문래동', value: '문래동' },
    { label: '신길동', value: '신길동' },
    { label: '양평동', value: '양평동' },
    { label: '여의도동', value: '여의도동' },
    { label: '영등포동', value: '영등포동' },
  ],
  용산구: [
    { label: '갈월동', value: '갈월동' },
    { label: '남영동', value: '남영동' },
    { label: '도원동', value: '도원동' },
    { label: '동빙고동', value: '동빙고동' },
    { label: '문배동', value: '문배동' },
    { label: '보광동', value: '보광동' },
    { label: '산천동', value: '산천동' },
    { label: '서계동', value: '서계동' },
    { label: '서빙고동', value: '서빙고동' },
    { label: '신계동', value: '신계동' },
    { label: '용문동', value: '용문동' },
    { label: '원효로동', value: '원효로동' },
    { label: '이촌동', value: '이촌동' },
    { label: '이태원동', value: '이태원동' },
    { label: '주성동', value: '주성동' },
    { label: '청암동', value: '청암동' },
    { label: '한강로동', value: '한강로동' },
    { label: '한남동', value: '한남동' },
    { label: '효창동', value: '효창동' },
    { label: '후암동', value: '후암동' },
  ],
  은평구: [
    { label: '갈현동', value: '갈현동' },
    { label: '구산동', value: '구산동' },
    { label: '녹번동', value: '녹번동' },
    { label: '대조동', value: '대조동' },
    { label: '불광동', value: '불광동' },
    { label: '수색동', value: '수색동' },
    { label: '신사동', value: '신사동' },
    { label: '역촌동', value: '역촌동' },
    { label: '응암동', value: '응암동' },
    { label: '증산동', value: '증산동' },
    { label: '진관동', value: '진관동' },
  ],
  종로구: [
    { label: '청운효자동', value: '청운효자동' },
    { label: '사직동', value: '사직동' },
    { label: '삼청동', value: '삼청동' },
    { label: '부암동', value: '부암동' },
    { label: '평창동', value: '평창동' },
    { label: '무악동', value: '무악동' },
    { label: '교남동', value: '교남동' },
    { label: '가회동', value: '가회동' },
    { label: '종로1.2.3.4가동', value: '종로1.2.3.4가동' },
    { label: '종로5.6가동', value: '종로5.6가동' },
    { label: '이화동', value: '이화동' },
    { label: '혜화동', value: '혜화동' },
    { label: '창신1동', value: '창신1동' },
    { label: '창신2동', value: '창신2동' },
    { label: '창신3동', value: '창신3동' },
    { label: '숭인1동', value: '숭인1동' },
    { label: '숭인2동', value: '숭인2동' },
  ],
  중구: [
    { label: '광희동', value: '광희동' },
    { label: '남대문로동', value: '남대문로동' },
    { label: '다산동', value: '다산동' },
    { label: '동화동', value: '동화동' },
    { label: '명동', value: '명동' },
    { label: '소공동', value: '소공동' },
    { label: '신당동', value: '신당동' },
    { label: '을지로동', value: '을지로동' },
    { label: '장충동', value: '장충동' },
    { label: '중림동', value: '중림동' },
    { label: '필동', value: '필동' },
    { label: '황학동', value: '황학동' },
  ],
  중랑구: [
    { label: '망우동', value: '망우동' },
    { label: '면목동', value: '면목동' },
    { label: '묵동', value: '묵동' },
    { label: '상봉동', value: '상봉동' },
    { label: '신내동', value: '신내동' },
    { label: '중화동', value: '중화동' },
  ],
};
