# JVM / 메모리
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.java.home=/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home

# AndroidX
android.useAndroidX=true

# RN 기본 플래그
newArchEnabled=false
hermesEnabled=true
edgeToEdgeEnabled=false

# SDK/툴체인 버전 
minSdkVersion=31
compileSdkVersion=35
targetSdkVersion=35
buildToolsVersion=35.0.0
ndkVersion=26.3.11579264